version: '3.8'

services:
  region-middleware:
    container_name: regionmiddleware
    build:
      context: ./regionmiddleware
      dockerfile: Dockerfile
    ports:
      - "8686:8080"
    restart: unless-stopped
    env_file:
      - .env